In [1]:
import numpy as np
import pandas as pd
import random

Ejercicio 1. ¿Qué diferencia hay entre una Serie y un DataFrame?

In [2]:
# Las Series tienen una dimensión(índices) y los DataFrames tienes 2 dimensiones (índices y columnas).

Ejercicio 2. Momento de trabajar con Series.

In [3]:
valores = np.random.randint(1,50,(7))
valores

array([20, 16, 18, 12, 30, 49, 35])

In [4]:
indices = ["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"]
indices

['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']

In [5]:
# convertimos las dos listas a serie

semana = pd.Series(valores, indices)
semana

Lunes        20
Martes       16
Miercoles    18
Jueves       12
Viernes      30
Sabado       49
Domingo      35
dtype: int64

In [6]:
# A partir de las dos listas anteriores cread un diccionario usando un bucle for. 
# Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez.

diccionario = dict(zip(indices, valores))
diccionario

{'Lunes': 20,
 'Martes': 16,
 'Miercoles': 18,
 'Jueves': 12,
 'Viernes': 30,
 'Sabado': 49,
 'Domingo': 35}

In [7]:
# Crea una Serie con el diccionario creado en el punto anterior.

semana2 = pd.Series(diccionario)
semana2

Lunes        20
Martes       16
Miercoles    18
Jueves       12
Viernes      30
Sabado       49
Domingo      35
dtype: int64

In [8]:
# ¿Qué forma tiene esta última Serie?

semana2.shape

(7,)

In [33]:
# ¿Qué tipo de datos tiene?

semana2.dtypes

dtype('int64')

In [10]:
# ¿Qué tamaño tiene?

semana2.size

7

In [11]:
# ¿Cuáles son los índices de la Serie?

semana2.index

Index(['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado',
       'Domingo'],
      dtype='object')

In [12]:
# ¿Y los values?

semana2.values

array([20, 16, 18, 12, 30, 49, 35])

In [13]:
# Extraed el valor para el índice "lunes".

semana2["Lunes"]

20

In [35]:
# Extraed el valor para el índice "lunes", "martes" y "miércoles".

semana2["Lunes" : "Miercoles"]

Lunes        20
Martes       16
Miercoles    18
dtype: int64

In [15]:
# Extraed el valor para el índice "lunes" y "domingo".

semana2[["Lunes", "Domingo"]]

Lunes      20
Domingo    35
dtype: int64

Ejercicio 3. Es el turno de los DataFrames

In [16]:
# Cread un array de dos dimensiones con 4 filas y 3 columnas.

array1 = np.random.randint(1,50,(4, 3))
array1

array([[30, 18,  3],
       [43, 32, 11],
       [27, 12, 41],
       [20, 23,  8]])

In [17]:
# Convertid el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

paises = pd.DataFrame(array1, columns =["España", "Francia", "Italia"])
paises

España  Francia  Italia
0      30       18       3
1      43       32      11
2      27       12      41
3      20       23       8

In [20]:
# Descargad el archivo "medallas" y cargad el DataFrame con la siguiente línea de código:

df = pd.read_csv("medallas.csv", index_col=["País"])


In [36]:
# Usando el loc extraed todas las columnas de la fila.

df.loc[:]



Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [46]:
# Usando el loc extraed todas las columnas de China e Irán.

df.loc[["China", "Irán"],]



Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

In [47]:
# Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

df.loc[["China", "Irán"], ["Oro", "Plata", "Bronce"]]

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197