In [21]:
import numpy as np

1. Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:

In [22]:
array_1 = np.random.rand(5,3).round(2)
array_1

array([[0.46, 0.85, 0.4 ],
       [0.03, 0.42, 0.13],
       [0.98, 0.22, 0.41],
       [0.28, 0.62, 0.04],
       [0.76, 0.8 , 0.62]])

El valor de la primera fila y la segunda columna.

In [23]:
array_1[0,1]

0.85

Los valores de la segunda fila y las dos primeras columnas.

In [24]:
array_1[1,:2]

array([0.03, 0.42])

Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [25]:
array_1[0::2,:]

array([[0.46, 0.85, 0.4 ],
       [0.98, 0.22, 0.41],
       [0.76, 0.8 , 0.62]])

Extraed los valores que sean mayores que 0.5.

In [26]:
array_1[array_1>0.5]

array([0.85, 0.98, 0.62, 0.76, 0.8 , 0.62])

Extraed los valores menores que 0.2 o mayores que 0.5

In [27]:
array_1[(array_1<0.2) | (array_1>0.5)]

array([0.85, 0.03, 0.13, 0.98, 0.62, 0.04, 0.76, 0.8 , 0.62])

2. Cread dos array de tres dimensiones:

El primero de 2 matrices, 5 filas y 3 columnas.

In [31]:
array_2 = np.random.rand(2,5,3).round(2)
print(array_2)


[[[0.24 0.2  0.32]
  [0.31 0.32 0.74]
  [0.61 0.21 0.9 ]
  [0.22 0.35 0.58]
  [0.61 0.54 0.49]]

 [[0.99 0.29 0.53]
  [0.27 0.77 0.98]
  [0.43 0.77 0.38]
  [0.72 0.71 0.98]
  [0.16 0.61 0.74]]]


El segundo de 3 matrices, 2 filas y 5 columnas

In [32]:
array_3 = np.random.rand(3,2,5).round(2)
print(array_3)

[[[0.63 0.82 0.63 0.52 0.25]
  [0.9  0.99 0.85 0.27 0.68]]

 [[0.21 0.42 0.99 0.56 0.13]
  [0.4  0.66 0.1  0.37 0.47]]

 [[0.39 0.72 0.8  0.55 0.19]
  [0.22 0.61 0.16 0.48 0.32]]]


Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [33]:
def informar_arrays(array_a_comprobar):
    array_a_comprobar.shape
    array_a_comprobar.size
    array_a_comprobar.dtype
    array_a_comprobar.ndim
    return print(f"La forma de nuestra array es {array_a_comprobar.shape}. El tamaño de nuestra array es de {array_a_comprobar.size}. El tipo de nuestra array es {array_a_comprobar.dtype}. Y la dimensión de nuestra array es {array_a_comprobar.ndim}.")

In [34]:
informar_arrays(array_2)

La forma de nuestra array es (2, 5, 3). El tamaño de nuestra array es de 30. El tipo de nuestra array es float64. Y la dimensión de nuestra array es 3.


In [36]:
informar_arrays(array_3)

La forma de nuestra array es (3, 2, 5). El tamaño de nuestra array es de 30. El tipo de nuestra array es float64. Y la dimensión de nuestra array es 3.


Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [37]:
np.add(array_2,array_3)

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

No se puede sumar porque las dos *arrays* no tienen la misma *shape*/forma.

Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
- reshape()
- transpose()

In [39]:
array_3_cambiada = np.transpose(array_3,(1,2,0))
array_3_cambiada

array([[[0.63, 0.21, 0.39],
        [0.82, 0.42, 0.72],
        [0.63, 0.99, 0.8 ],
        [0.52, 0.56, 0.55],
        [0.25, 0.13, 0.19]],

       [[0.9 , 0.4 , 0.22],
        [0.99, 0.66, 0.61],
        [0.85, 0.1 , 0.16],
        [0.27, 0.37, 0.48],
        [0.68, 0.47, 0.32]]])

In [40]:
array_3_shape = np.reshape(array_3,(2,5,3))
array_3_shape

array([[[0.63, 0.82, 0.63],
        [0.52, 0.25, 0.9 ],
        [0.99, 0.85, 0.27],
        [0.68, 0.21, 0.42],
        [0.99, 0.56, 0.13]],

       [[0.4 , 0.66, 0.1 ],
        [0.37, 0.47, 0.39],
        [0.72, 0.8 , 0.55],
        [0.19, 0.22, 0.61],
        [0.16, 0.48, 0.32]]])

Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [41]:
array_suma = np.add(array_2,array_3_cambiada)
array_suma

array([[[0.87, 0.41, 0.71],
        [1.13, 0.74, 1.46],
        [1.24, 1.2 , 1.7 ],
        [0.74, 0.91, 1.13],
        [0.86, 0.67, 0.68]],

       [[1.89, 0.69, 0.75],
        [1.26, 1.43, 1.59],
        [1.28, 0.87, 0.54],
        [0.99, 1.08, 1.46],
        [0.84, 1.08, 1.06]]])

In [42]:
array_resta = np.subtract(array_2,array_3_shape)
array_resta

array([[[-0.39, -0.62, -0.31],
        [-0.21,  0.07, -0.16],
        [-0.38, -0.64,  0.63],
        [-0.46,  0.14,  0.16],
        [-0.38, -0.02,  0.36]],

       [[ 0.59, -0.37,  0.43],
        [-0.1 ,  0.3 ,  0.59],
        [-0.29, -0.03, -0.17],
        [ 0.53,  0.49,  0.37],
        [ 0.  ,  0.13,  0.42]]])

In [46]:
array_multi = np.multiply(array_2, array_3_cambiada).round(2)
array_multi

array([[[0.15, 0.04, 0.12],
        [0.25, 0.13, 0.53],
        [0.38, 0.21, 0.72],
        [0.11, 0.2 , 0.32],
        [0.15, 0.07, 0.09]],

       [[0.89, 0.12, 0.12],
        [0.27, 0.51, 0.6 ],
        [0.37, 0.08, 0.06],
        [0.19, 0.26, 0.47],
        [0.11, 0.29, 0.24]]])

In [45]:
array_division = np.divide(array_2,array_3_shape).round(2)
array_division

array([[[0.38, 0.24, 0.51],
        [0.6 , 1.28, 0.82],
        [0.62, 0.25, 3.33],
        [0.32, 1.67, 1.38],
        [0.62, 0.96, 3.77]],

       [[2.47, 0.44, 5.3 ],
        [0.73, 1.64, 2.51],
        [0.6 , 0.96, 0.69],
        [3.79, 3.23, 1.61],
        [1.  , 1.27, 2.31]]])