In [15]:
import numpy as np

Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 
columnas cuyos valores solo tengan 1 decimales. 

In [22]:
array = np.round(np.random.random_sample((2,3,5)), decimals = 1)
array

array([[[0.1, 0.1, 0.1, 1. , 0.7],
        [0.4, 0.1, 0.7, 0. , 0.8],
        [0.6, 0.6, 0.6, 0. , 0.5]],

       [[0.9, 0.2, 0.8, 0.3, 0.1],
        [0.9, 0.1, 0.6, 0.9, 1. ],
        [0.5, 0.9, 0.3, 0.6, 0.3]]])

Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [23]:
array_media = np.round(np.mean(array),decimals = 1)
array_media

0.5

Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [24]:
array_max = np.round(np.max(array),decimals = 1)
array_max

1.0

Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [25]:
array_min = np.round(np.min(array), decimals = 1)
array_min

0.0

Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.

In [26]:
array_vacio = np.empty_like(array, str)
array_vacio

#Teniendo en cuenta que tendré que sostituir letras con numeros, pido que el array vacio
#tenga strings

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [98]:
array_media = np.round(np.mean(array), decimals = 1)
array_max = np.round(np.max(array), decimals = 1)
array_min = np.round(np.min(array), decimals = 1)

for matriz in range(len(array)):
    #print(matriz) 
    for fila in range(len(array[matriz])):
            #print(fila)
            for columna in range(len(array[matriz][fila])):
                #print(columna)
                if array[matriz][fila][columna] == array_media:
                    array_vacio[matriz][fila][columna] = "A"
                elif array[matriz][fila][columna] == array_max:
                    array_vacio[matriz][fila][columna] = "D"
                elif array[matriz][fila][columna] == array_min:
                    array_vacio[matriz][fila][columna] = "E"
                elif array[matriz][fila][columna] < array_media:
                    array_vacio[matriz][fila][columna] = "C"
                elif array[matriz][fila][columna] > array_media:
                    array_vacio[matriz][fila][columna] = "B"
                
array_letras = array_vacio.copy()
print(array_letras)

[[['C' 'C' 'C' 'D' 'B']
  ['C' 'C' 'B' 'E' 'B']
  ['B' 'B' 'B' 'E' 'A']]

 [['B' 'C' 'B' 'C' 'C']
  ['B' 'C' 'B' 'B' 'D']
  ['A' 'B' 'C' 'B' 'C']]]


Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. 


-- Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1

-- Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2

-- Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

In [108]:
values(array_letras)

NameError: name 'values' is not defined

In [109]:
unidemnsional = []

for value in array_letras:
    #print(value)
    for subvalue in value:
        #print(subvalue)
        for subvalue2 in subvalue:    
            #print(subvalue2)
            if np.any(subvalue2 == "A"):
                unidemnsional.append(1,)
            elif np.any(subvalue2 == "B"):
                unidemnsional.append(1,)
            elif np.any(subvalue2 == "C"):
                unidemnsional.append(2,)
            elif np.any(subvalue2 == "D"):
                unidemnsional.append(2,)
            else:
                unidemnsional.append(3,)

print(unidemnsional)

[2, 2, 2, 2, 1, 2, 2, 1, 3, 1, 1, 1, 1, 3, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2]


Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.

In [110]:
array_unidemnsional = np.array(unidemnsional)
array_unidemnsional

array([2, 2, 2, 2, 1, 2, 2, 1, 3, 1, 1, 1, 1, 3, 1, 1, 2, 1, 2, 2, 1, 2,
       1, 1, 2, 1, 1, 2, 1, 2])

In [111]:
array_final = np.reshape(array_unidemnsional,(2,3,5))

array_final

array([[[2, 2, 2, 2, 1],
        [2, 2, 1, 3, 1],
        [1, 1, 1, 3, 1]],

       [[1, 2, 1, 2, 2],
        [1, 2, 1, 1, 2],
        [1, 1, 2, 1, 2]]])

------------------------------------------------------------------------------------------

Otra forma

In [35]:
array_1 = np.empty(30)
array_1

array([0.94308059, 0.4456214 , 0.5734602 , 0.41318416, 0.12175674,
       0.39093774, 0.0336535 , 0.46264478, 0.68491035, 0.2491607 ,
       0.92984855, 0.24130013, 0.38079644, 0.30926805, 0.00678156,
       0.82417153, 0.97801406, 0.38460766, 0.20512525, 0.50082044,
       0.88519793, 0.74233133, 0.77672805, 0.27783531, 0.86868783,
       0.03545535, 0.39874504, 0.53298827, 0.37693497, 0.56949674])

In [85]:
array_letras.shape

(2, 3, 5)

In [116]:
for matriz in array_letras:
    #print(letras) 
    for filas in matriz:
            #print(columna)
            for letras in filas:
                #print(fila)
                    if array_letras(letras) == "A":
                       array_1[array_letras("A")].append(1,)
                    elif np.any(subvalue2 == "B"):
                        unidemnsional.append(1,)
                    elif np.any(subvalue2 == "C"):
                        unidemnsional.append(2,)
                    elif np.any(subvalue2 == "D"):
                        unidemnsional.append(2,)
                    else:
                        unidemnsional.append(3,)


TypeError: 'numpy.ndarray' object is not callable

In [59]:
array_1

array([1.        , 1.        , 2.        , 1.        , 2.        ,
       0.39093774, 0.0336535 , 0.46264478, 0.68491035, 0.2491607 ,
       0.92984855, 0.24130013, 0.38079644, 0.30926805, 0.00678156,
       0.82417153, 0.97801406, 0.38460766, 0.20512525, 0.50082044,
       0.88519793, 0.74233133, 0.77672805, 0.27783531, 0.86868783,
       0.03545535, 0.39874504, 0.53298827, 0.37693497, 0.56949674])

In [56]:
array_1[9]

0.2491607019231078