In [3]:
import numpy as np
import random

1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [20]:
np.random.seed(42)
arr_1 = np.random.random_sample((2,5))
np.random.seed(42)
arr_2 = np.random.random_sample((2,5))

In [21]:
#Aqui podemos ver que los dos arrays son iguales
print(arr_1)
print(arr_2)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]]
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]]


2. Cread los siguientes arrays:
    
    - Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

    - Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [73]:
arr_uniforme =np.round(np.random.uniform(0,10, size=(2,3,5)))
arr_uniforme

array([[[ 3.,  2.,  9.,  6.,  4.],
        [ 5.,  9.,  2.,  6.,  5.],
        [ 6.,  0.,  9.,  9.,  6.]],

       [[ 7.,  9.,  7.,  2.,  6.],
        [ 6.,  4.,  7.,  9.,  9.],
        [ 5.,  1., 10.,  8.,  1.]]])

In [29]:
arr_bin = np.random.binomial(10, 0.3, size = (2,3,5))
arr_bin

array([[[3, 2, 1, 2, 5],
        [2, 3, 4, 2, 6],
        [6, 2, 3, 2, 2]],

       [[1, 3, 3, 1, 2],
        [5, 2, 1, 3, 6],
        [2, 4, 4, 2, 4]]])

3. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

    --    ⚠️ Explicar cada uno de los outputs que os salgan. --

    --    Que significa cada una de estas operaciones que hemos ido extrayendo? --

- Elementos comunes entre los dos arrays

In [40]:
arr_unique_1 = np.unique(arr_uniforme)
arr_unique_1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
arr_unique_2 = np.unique(arr_bin)
arr_unique_2

array([1, 2, 3, 4, 5, 6])

In [45]:
arr_comunes = np.intersect1d(arr_unique_1,arr_unique_2)
arr_comunes

# hemos mirado los elementos unicos de los arrays con el metodo unique, porque como son de tres dimensiones así nos devolvia un array de una dimension.
# Asi podiamos usar el metodo intersect1d que solo admite una array de una dimension.

array([1., 2., 3., 4., 5., 6.])

- Unión de los dos arrays

In [48]:
arr_union = np.union1d(arr_unique_1,arr_unique_2)
arr_union

# Siguiendo el exemplo de antes usamos el metodo union para unir los valores unicos de cada array.


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

In [50]:
print(arr_unique_1)
print(arr_unique_2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1 2 3 4 5 6]


In [49]:
arr_diferencia = np.setdiff1d(arr_unique_1, arr_unique_2)
arr_diferencia

# nos devuelve los elementos unicos que hay en la array_1 pero no hay en la array_2.

array([ 0.,  7.,  8.,  9., 10.])

4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

In [57]:
array1 = np.random.randint(1,100, 80)
array2 = np.random.randint(1,100, 80)

print(array1)
print(array2)

[42 41  6 52 26 64 98 59 56 59 70 33 53 22 21 70 70  4 94 75 62 62 94 95
 24 55  9  3 31 40 36 24 95  6 66 84 92 75  4 79  6 94 51 62 57 66 79 75
  8 26 51 45 44  5 70 26 68 19 84 97 20 12 47  1 90 14 64 38 37 11 77  3
 33  6 50 10  5 23 10 44]
[ 2 13 40  2 84 65 63 73 17  9 75 15 24 38 35 94 95 49 69 62 60 50 78 75
  9 34 76 99 35  1 40 64 22 60 64 93 72 11 14 60 30 35 85 37  5 83 78 26
 62  4 89 42 89 18 40 72 39 14 32 51 38 97 23 63 15 97 25 17 97 66 78 53
 51 39 51 70  6 67  7 51]


- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [58]:
array1 = np.unique(array1)
array2 = np.unique(array2)

print(array1)
print(array2)

[ 1  3  4  5  6  8  9 10 11 12 14 19 20 21 22 23 24 26 31 33 36 37 38 40
 41 42 44 45 47 50 51 52 53 55 56 57 59 62 64 66 68 70 75 77 79 84 90 92
 94 95 97 98]
[ 1  2  4  5  6  7  9 11 13 14 15 17 18 22 23 24 25 26 30 32 34 35 37 38
 39 40 42 49 50 51 53 60 62 63 64 65 66 67 69 70 72 73 75 76 78 83 84 85
 89 93 94 95 97 99]


- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [59]:
array3 = np.setdiff1d(array1, array2)
array3

array([ 3,  8, 10, 12, 19, 20, 21, 31, 33, 36, 41, 44, 45, 47, 52, 55, 56,
       57, 59, 68, 77, 79, 90, 92, 98])

- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [60]:
array4 = np.setdiff1d(array2, array1)
array4

array([ 2,  7, 13, 15, 17, 18, 25, 30, 32, 34, 35, 39, 49, 60, 63, 65, 67,
       69, 72, 73, 76, 78, 83, 85, 89, 93, 99])

- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [61]:
array5 = np.intersect1d(array1,array2)
array5

array([ 1,  4,  5,  6,  9, 11, 14, 22, 23, 24, 26, 37, 38, 40, 42, 50, 51,
       53, 62, 64, 66, 70, 75, 84, 94, 95, 97])

- ¿Cuál es la relación que existe entre todos estos arrays?



In [63]:
print(len(array1))
print(len(array2))
print(len(array3))
print(len(array4))
print(len(array5))


52
54
25
27
27


In [64]:
(len(array1) + len(array2)) == len(array3)

False

In [65]:
len(array5) + (len(array4)) == len(array2)

True

In [71]:
len(array5) + (len(array3)) == len(array1)

True

    --💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados. --